services:
  frontend:
    build: ./frontend
    image: krishsoh/youtube-frontend:latest
    ports:
      - "3000:8080"
    environment:
      - BACKEND_URL=http://backend:5000
      - API_PROXY_URL=http://api-proxy:4000
    depends_on:
      - backend
      - api-proxy
    restart: unless-stopped

  backend:
    build: ./backend
    image: krishsoh/youtube-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  api-proxy:
    build: ./api-proxy
    image: krishsoh/youtube-api-proxy:latest
    ports:
      - "4000:4000"
    env_file:
      - ./api-proxy/.env
    restart: unless-stopped
